export const islandEntitiesConfig = {
  defi: [
    {
      id: 'defi-zone-a',
      name: 'Hot Yield Hub',
      color: '#38bdf8',
      anchor: { angle: 0.35, distance: 0.42, height: 2 },
      movement: { radius: 3, speed: 0.22 },
      modelPath: '/models/sheep.glb',
      modelScale: [2, 2, 2],
      modelRotation: [0, 0, 0],
      modelOffset: [0, 0, 0],
      zoneSection: 'Hot dApps',
      description: 'Highlights the top-performing DeFi protocols on Monad.',
      zoneDataKey: 'hot',
    },
    {
      id: 'defi-zone-b',
      name: 'New Market Relay',
      color: '#f97316',
      anchor: { angle: 2.25, distance: 0.38, height: 1.6 },
      zoneSection: 'Newcomers',
      description: 'Surfacing newly launched DeFi products and liquidity programs.',
      zoneDataKey: 'newcomers',
    },
    {
      id: 'defi-zone-c',
      name: 'Mission Terminal',
      color: '#22c55e',
      anchor: { angle: 4.4, distance: 0.46, height: 1.8 },
      zoneSection: 'Quest Focus',
      description: 'Access the latest DeFi quest objectives and reward ladders.',
      zoneDataKey: 'quest',
    },
  ],
  gaming: [
    {
      id: 'gaming-zone-a',
      name: 'Arcade Beacon',
      color: '#f472b6',
      anchor: { angle: -0.4, distance: 0.44, height: 2 },
      movement: { radius: 2.6, speed: 0.28 },
      modelPath: '/models/sheep.glb',
      modelScale: [2, 2, 2],
      modelRotation: [0, 0, 0],
      modelOffset: [0, 0, 0],
      zoneSection: 'Hot dApps',
      description: 'Tracks the most active Monad gaming experiences.',
      zoneDataKey: 'hot',
    },
    {
      id: 'gaming-zone-b',
      name: 'Launch Pad',
      color: '#fde047',
      anchor: { angle: 1.9, distance: 0.4, height: 1.7 },
      zoneSection: 'Newcomers',
      description: 'Introduces new games entering alpha and beta phases.',
      zoneDataKey: 'newcomers',
    },
    {
      id: 'gaming-zone-c',
      name: 'Quest Uplink',
      color: '#22d3ee',
      anchor: { angle: 3.9, distance: 0.43, height: 1.9 },
      zoneSection: 'Quest Focus',
      description: 'Synchronizes gaming quests and leaderboard missions.',
      zoneDataKey: 'quest',
    },
  ],
  infra: [
    {
      id: 'infra-zone-a',
      name: 'Network Scanner',
      color: '#67e8f9',
      anchor: { angle: 0.25, distance: 0.4, height: 2 },
      movement: { radius: 2.8, speed: 0.24 },
      modelPath: '/models/sheep.glb',
      modelScale: [2, 2, 2],
      modelRotation: [0, 0, 0],
      modelOffset: [0, 0, 0],
      zoneSection: 'Hot dApps',
      description: 'Broadcasts updates for core infra services and tooling.',
      zoneDataKey: 'hot',
    },
    {
      id: 'infra-zone-b',
      name: 'Onboarding Array',
      color: '#a855f7',
      anchor: { angle: 2.3, distance: 0.37, height: 1.7 },
      zoneSection: 'Newcomers',
      description: 'Curates upcoming infra projects joining the ecosystem.',
      zoneDataKey: 'newcomers',
    },
    {
      id: 'infra-zone-c',
      name: 'Mission Console',
      color: '#22c55e',
      anchor: { angle: 4.3, distance: 0.45, height: 1.8 },
      zoneSection: 'Quest Focus',
      description: 'Access infrastructure quests and integration tracks.',
      zoneDataKey: 'quest',
    },
  ],
  wallet: [
    {
      id: 'wallet-zone-a',
      name: 'Vault Sentinel',
      color: '#c084fc',
      anchor: { angle: -0.3, distance: 0.42, height: 1.9 },
      movement: { radius: 2.4, speed: 0.22 },
      modelPath: '/models/sheep.glb',
      modelScale: [2, 2, 2],
      modelRotation: [0, 0, 0],
      modelOffset: [0, 0, 0],
      zoneSection: 'Hot dApps',
      description: 'Guides users toward flagship wallet experiences.',
      zoneDataKey: 'hot',
    },
    {
      id: 'wallet-zone-b',
      name: 'Key Encoder',
      color: '#34d399',
      anchor: { angle: 1.8, distance: 0.39, height: 1.6 },
      zoneSection: 'Newcomers',
      description: 'Showcases new wallet products and recovery flows.',
      zoneDataKey: 'newcomers',
    },
    {
      id: 'wallet-zone-c',
      name: 'Quest Console',
      color: '#fde68a',
      anchor: { angle: 3.85, distance: 0.44, height: 1.8 },
      zoneSection: 'Quest Focus',
      description: 'Lines up wallet-centric tasks and community missions.',
      zoneDataKey: 'quest',
    },
  ],
  art: [
    {
      id: 'art-zone-a',
      name: 'Glitch Muse',
      color: '#f9a8d4',
      anchor: { angle: 0.1, distance: 0.41, height: 2.1 },
      movement: { radius: 2.9, speed: 0.24 },
      modelPath: '/models/sheep.glb',
      modelScale: [2, 2, 2],
      modelRotation: [0, 0, 0],
      modelOffset: [0, 0, 0],
      zoneSection: 'Hot dApps',
      description: 'Spotlights trending art drops and creator collaborations.',
      zoneDataKey: 'hot',
    },
    {
      id: 'art-zone-b',
      name: 'Gallery Node',
      color: '#facc15',
      anchor: { angle: 2.1, distance: 0.38, height: 1.8 },
      zoneSection: 'Newcomers',
      description: 'Hosts new artists and collections entering the gallery.',
      zoneDataKey: 'newcomers',
    },
    {
      id: 'art-zone-c',
      name: 'Quest Archive',
      color: '#34d399',
      anchor: { angle: 4.25, distance: 0.46, height: 1.9 },
      zoneSection: 'Quest Focus',
      description: 'Curated hub for art quests and collector achievements.',
      zoneDataKey: 'quest',
    },
  ],
}

export default islandEntitiesConfig

